name: Transfer new photo sequence
on:
  push:
    paths:
      - .github/workflows/transfer-new-photos.yml
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: na-avenida-fotos-novas
          path: Imagem do ChatGPT 27 de set. de 2026, *.png
          compression-level: 0
